"""Adicionar coluna valores_depositos

Revision ID: b9e42e2ca3c6
Revises: 
Create Date: 2024-09-09 18:53:46.628114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e42e2ca3c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desafio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valores_depositos', sa.String(), nullable=True))
        batch_op.alter_column('depositos_feitos',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desafio', schema=None) as batch_op:
        batch_op.alter_column('depositos_feitos',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('valores_depositos')

    # ### end Alembic commands ###
