"""Initial migration

Revision ID: 49c39c01de01
Revises: 
Create Date: 2024-09-11 19:05:12.546640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c39c01de01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=456), nullable=True),
    sa.Column('telefone_numero', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('userfeedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=1500), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desafio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('meta', sa.Float(), nullable=False),
    sa.Column('depositos_totais', sa.Integer(), nullable=False),
    sa.Column('depositos_feitos', sa.String(), nullable=True),
    sa.Column('valor_investido', sa.Float(), nullable=True),
    sa.Column('valores_depositos', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('valor_maximo_aporte', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desafio_id', sa.Integer(), nullable=False),
    sa.Column('convidado_id', sa.Integer(), nullable=False),
    sa.Column('aceito', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['convidado_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['desafio_id'], ['desafio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('convite')
    op.drop_table('desafio')
    op.drop_table('userfeedback')
    op.drop_table('user')
    # ### end Alembic commands ###
