"""Add is_admin field to User model

Revision ID: 795fa9e974e9
Revises: 7a928dc97cda
Create Date: 2024-09-12 13:11:10.278169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795fa9e974e9'
down_revision = '7a928dc97cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
