"""Add is_active column to User model

Revision ID: 7a928dc97cda
Revises: 138811a36132
Create Date: 2024-09-12 13:02:33.950333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a928dc97cda'
down_revision = '138811a36132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=456),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=456),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
